export const selectList = [
	{
		title: "Background",
		type: "background",
		items: [
			{ value: "disabled", label: "Select Background", disabled: true },
			{ value: "bg-white", label: "White" },
			{ value: "bg-purple", label: "Purple" },
			{ value: "bg-green", label: "Green" },
			{ value: "bg-blue", label: "Blue" },
			{ value: "bg-yellow", label: "Yellow" },
			{ value: "bg-orange", label: "Orange" },
			{ value: "bg-red", label: "Red" },
			{ value: "bg-water", label: "Water" },
			{ value: "bg-honey", label: "Honey" },
			{ value: "bg-wood", label: "Wood" },
		],
	},
	{
		title: "Fur",
		type: "bears",
		items: [
			{ value: "disabled", label: "Select Fur", disabled: true },
			{ value: "fur-cream", label: "Cream" },
			{ value: "fur-zombie", label: "Zombie" },
			{ value: "fur-brown", label: "Brown" },
			{ value: "fur-ginger", label: "Ginger" },
			{ value: "fur-sand", label: "Sand" },
			{ value: "fur-charcoal", label: "Charcoal" },
			{ value: "fur-periwinkle", label: "Periwinkle" },
			{ value: "fur-rose", label: "Rose" },
			{ value: "fur-alien", label: "Alien" },
			{ value: "fur-panda", label: "Panda" },
		],
	},
	{
		title: "Clothes",
		type: "clothes",
		items: [
			{ value: "disabled", label: "Select Clothes", disabled: true },
			{ value: "none", label: "None" },
			{ value: "suit", label: "Suit" },
			{ value: "plaid-shirt", label: "Plaid Shirt" },
			{ value: "hoodie-black", label: "Hoodie Black" },
			{ value: "hoodie-white", label: "Hoodie White" },
			{ value: "hoodie-mint", label: "Hoodie Mint" },
			{ value: "t-shirt-white", label: "T-shirt White" },
			{ value: "t-shirt-orange", label: "T-shirt Orange" },
			{ value: "tanktop", label: "Tanktop" },
			{ value: "plaid-shirt-red", label: "Plaid-shirt Red" },
			{ value: "pirate-shirt", label: "Pirate shirt" },
		],
	},
	{
		title: "Mouth",
		type: "mouth",
		items: [
			{ value: "disabled", label: "Select Mouth", disabled: true },
			{ value: "none", label: "None" },
			{ value: "beard", label: "Beard" },
			{ value: "black-face-mask", label: "Black face mask" },
		],
	},
	{
		title: "Eyes",
		type: "eyes",
		items: [
			{ value: "disabled", label: "Select Eyes", disabled: true },
			{ value: "none", label: "None" },
			{ value: "sun-glasses", label: "Sun Glasses" },
			{ value: "diamond-glasses", label: "Diamond Glasses" },
			{ value: "gold-glasses", label: "Gold Glasses" },
		],
	},
	{
		title: "Head",
		type: "head",
		items: [
			{ value: "disabled", label: "Select Head", disabled: true },
			{ value: "none", label: "None" },
			{ value: "halo", label: "Halo" },
			{ value: "top-hat", label: "Top Hat" },
			{ value: "head-cap-black", label: "Cap-black Hat" },
			{ value: "head-fedora-tan", label: "Fedora-tan Hat" },
			{ value: "head-hard-hat", label: "Hard Hat" },
			{ value: "head-viking-helmet", label: "Viking Helmet" },
			{ value: "head-military-helmet", label: "Military Helmet" },
			{ value: "head-pirate-hat", label: "Pirate Hat" },
			{ value: "head-wizard-hat", label: "Wizard Hat" },
			{ value: "head-space-helmet", label: "Space Helmet" },
		],
	},
];

